# Generated by Django 3.2 on 2024-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
