# Generated by Django 3.2 on 2024-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
