# Generated by Django 3.2 on 2024-10-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Факты, которые пользователь хочет рассказать о себе.', verbose_name='Биография.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.SmallIntegerField(blank=True, help_text=('Присылается на почту при регистрации.', ' Используется для получения токена.'), null=True, verbose_name='Код подтверждения.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text=('Эмейл, он должен работать и принимать почту.',), max_length=254, unique=True, verbose_name='Эмейл.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Имя, желательно настоящее.', max_length=150, verbose_name='Имя.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Фамилия, тоже желательно настоящая.', max_length=150, verbose_name='Фамилия.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', help_text=('Пользователь может быть модератором,', ' админом или обычным юзером.'), max_length=16, verbose_name='Пользовательская роль.'),
        ),
    ]
