# Generated by Django 3.2 on 2024-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmate_code',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
    ]
